(function(g){var window=this;var BEa=function(a,b){return g.Sb(a,b)},l6=function(a){g.bn(a,"zx",g.ub());
return a},m6=function(a,b,c){g.wa(c)||(c=[String(c)]);
g.en(a.o,b,c)},CEa=function(a,b){var c=[];
g.Pk(b,function(a){try{var b=g.GD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.FD(b)&&c.push(a):c.push(a)},a);
return c},DEa=function(a,b){var c=CEa(a,b);
(0,g.D)(c,function(a){g.GD.prototype.remove.call(this,a)},a)},EEa=function(a){if(a.Md){if(a.Md.locationOverrideToken)return{locationOverrideToken:a.Md.locationOverrideToken};
if(null!=a.Md.latitudeE7&&null!=a.Md.longitudeE7)return{latitudeE7:a.Md.latitudeE7,longitudeE7:a.Md.longitudeE7}}return null},FEa=function(a,b,c,d){var e=new g.Tm(null,void 0);
a&&g.Um(e,a);b&&g.Vm(e,b);c&&g.Wm(e,c);d&&g.Xm(e,d);return e},GEa=function(a){g.pG[a]&&(a=g.pG[a],(0,g.D)(a,function(a){g.nG[a]&&delete g.nG[a]}),a.length=0)},HEa=function(a){var b=g.mG();
if(b)if(b.clear(a),a)GEa(a);else for(var c in g.pG)GEa(c)},n6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Nm;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",IEa(this,a.capabilities||""),JEa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},IEa=function(a,b){a.capabilities.clear();
(0,g.Xd)(b.split(","),g.Ca(BEa,KEa)).forEach(function(b){a.capabilities.add(b)})},JEa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},o6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},p6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},LEa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},MEa=function(a){return new o6(a)},NEa=function(a){return g.wa(a)?(0,g.J)(a,MEa):[]},q6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},r6=function(a){return g.wa(a)?"["+(0,g.J)(a,q6).join(",")+"]":"null"},s6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},OEa=function(a){return(0,g.J)(a,function(a){return{key:a.id,
name:a.name}})},t6=function(a,b){return g.Ha(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},u6=function(a,b){return g.Ha(a,function(a){return p6(a,b)})},PEa=function(){var a=(0,g.yH)();
a&&DEa(a,a.o.fe(!0))},v6=function(){var a=g.BH("yt-remote-connected-devices")||[];
g.db(a);return a},QEa=function(a){if(g.Na(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.J)(a,function(a,b){return 0==b?a:a.substring(c.length)})},REa=function(a){g.AH("yt-remote-connected-devices",a,86400)},x6=function(){if(w6)return w6;
var a=g.BH("yt-remote-device-id");a||(a=s6(),g.AH("yt-remote-device-id",a,31536E3));for(var b=v6(),c=1,d=a;g.Ma(b,d);)c++,d=a+"#"+c;return w6=d},y6=function(){var a=v6(),b=x6();
g.Ma(a,b);g.DH()&&g.fb(a,b);a=QEa(a);if(g.Na(a))try{g.XG("remote_sid")}catch(c){}else try{g.WG("remote_sid",a.join(","),-1)}catch(c){}},SEa=function(){return g.BH("yt-remote-session-browser-channel")},TEa=function(){return g.BH("yt-remote-local-screens")||[]},UEa=function(){g.AH("yt-remote-lounge-token-expiration",!0,86400)},VEa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.J)(TEa(),function(a){return a.loungeToken}),c=(0,g.J)(a,function(a){return a.loungeToken});
(0,g.Bm)(c,function(a){return!g.Ma(b,a)})&&UEa();
g.AH("yt-remote-local-screens",a,31536E3)},WEa=function(a,b){g.AH("yt-remote-session-browser-channel",a);
g.AH("yt-remote-session-screen-id",b);var c=v6(),d=x6();g.Ma(c,d)||c.push(d);REa(c);y6()},z6=function(a){a||(g.CH("yt-remote-session-screen-id"),g.CH("yt-remote-session-video-id"));
y6();a=v6();g.Sa(a,x6());REa(a)},XEa=function(){if(!A6){var a=g.RD();
a&&(A6=new g.AD(a))}return A6?!!A6.get("yt-remote-use-staging-server"):!1},YEa=function(){var a=window.document.createElement("a");
g.hd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.yb(a)},ZEa=function(a,b,c){c=void 0===c?null:c;
var d=g.Qd("SCRIPT");d.id=a;d.onload=function(){b&&(0,window.setTimeout)(b,0)};
d.onreadystatechange=function(){switch(d.readyState){case "loaded":case "complete":d.onload()}};
c&&d.setAttribute("nonce",c);g.jd(d,g.oe("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));a=window.document.getElementsByTagName("head")[0]||window.document.body;a.insertBefore(d,a.firstChild);return d},$Ea=function(a){a=void 0===a?null:a;
var b=YEa(),c=window.document.getElementById(b),d=c&&g.wF(c,"loaded");d||c&&!d||(c=ZEa(b,function(){g.wF(c,"loaded")||(g.vF(c,"loaded","true"),g.tG(b),g.wE(g.Ca(HEa,b),0))},a))},aFa=function(){var a=void 0===a?null:a;
window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):$Ea(a)},B6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},bFa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},C6=function(a){a.length?cFa(a.shift(),function(){C6(a)}):D6()},dFa=function(a){return"chrome-extension://"+a+E6},cFa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},F6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},D6=function(){var a=bFa();
a&&a(!1,"No cast extension found")},G6=function(){if(eFa){var a=2,b=bFa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;cFa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",D6,c)}},fFa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(G6(),a({command:"cast.sender.init"}))},gFa=function(){G6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);C6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+E6,"//www.gstatic.com/eureka/clank"+E6])},H6=function(a,b,c){g.L.call(this);
this.F=null!=c?(0,g.B)(a,c):a;this.Ed=b;this.D=(0,g.B)(this.hL,this);this.o=!1;this.A=0;this.B=this.Ga=null;this.C=[]},I6=function(){},J6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.jn(this);this.A=new g.Ag;this.A.setInterval(250)},iFa=function(a,b,c){a.Vj=1;
a.yh=l6(b.clone());a.hj=c;a.D=!0;hFa(a,null)},K6=function(a,b,c,d,e){a.Vj=1;
a.yh=l6(b.clone());a.hj=null;a.D=c;e&&(a.AF=!1);hFa(a,d)},hFa=function(a,b){a.Sk=(0,g.H)();
L6(a);a.Yh=a.yh.clone();m6(a.Yh,"t",a.F);a.Cn=0;a.Wc=a.o.Vs(a.o.tn()?b:null);0<a.Nt&&(a.Jq=new g.ul((0,g.B)(a.WG,a,a.Wc),a.Nt));a.Y.W(a.Wc,"readystatechange",a.IW);var c=a.Fi?g.bc(a.Fi):{};a.hj?(a.xr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Wc.send(a.Yh,a.xr,a.hj,c)):(a.xr="GET",a.AF&&!g.Kd&&(c.Connection="close"),a.Wc.send(a.Yh,a.xr,null,c));a.o.Gf(1)},lFa=function(a,b,c){for(var d=!0;!a.ni&&a.Cn<c.length;){var e=jFa(a,c);
if(e==M6){4==b&&(a.zh=4,N6(15),d=!1);break}else if(e==kFa){a.zh=4;N6(16);d=!1;break}else O6(a,e)}4==b&&0==c.length&&(a.zh=1,N6(17),d=!1);a.Nf=a.Nf&&d;d||(P6(a),Q6(a))},jFa=function(a,b){var c=a.Cn,d=b.indexOf("\n",c);
if(-1==d)return M6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return kFa;d+=1;if(d+c>b.length)return M6;var e=b.substr(d,c);a.Cn=d+c;return e},nFa=function(a,b){a.Sk=(0,g.H)();
L6(a);var c=b?window.location.hostname:"";a.Yh=a.yh.clone();g.bn(a.Yh,"DOMAIN",c);g.bn(a.Yh,"t",a.F);try{a.Of=new window.ActiveXObject("htmlfile")}catch(n){P6(a);a.zh=7;N6(22);Q6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in R6)k=R6[l];else if(l in mFa)k=R6[l]=mFa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=R6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.kd(g.zc("b/12014412"),d+"</body></html>");a.Of.open();a.Of.write(g.ad(c));a.Of.close();a.Of.parentWindow.m=(0,g.B)(a.MV,a);a.Of.parentWindow.d=(0,g.B)(a.JE,a,!0);a.Of.parentWindow.rpcClose=(0,g.B)(a.JE,a,!1);c=a.Of.createElement("DIV");a.Of.parentWindow.document.body.appendChild(c);d=g.Oc(a.Yh.toString());d=g.nb(g.Lc(d));d=g.kd(g.zc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.gd(c,g.ad(d));a.o.Gf(1)},
L6=function(a){a.Fx=(0,g.H)()+a.C;
oFa(a,a.C)},oFa=function(a,b){if(null!=a.ol)throw Error("WatchDog timer not null");
a.ol=S6((0,g.B)(a.cW,a),b)},T6=function(a){a.ol&&(g.x.clearTimeout(a.ol),a.ol=null)},Q6=function(a){a.o.OA()||a.ni||a.o.rq(a)},P6=function(a){T6(a);
g.lf(a.Jq);a.Jq=null;a.A.stop();g.pn(a.Y);if(a.Wc){var b=a.Wc;a.Wc=null;b.abort();b.dispose()}a.Of&&(a.Of=null)},O6=function(a,b){try{a.o.BE(a,b),a.o.Gf(4)}catch(c){}},qFa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;pFa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){qFa(a,b,c,d,f)},f)})}},pFa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{U6(d),c(!0)}catch(e){}};
d.onerror=function(){try{U6(d),c(!1)}catch(e){}};
d.onabort=function(){try{U6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{U6(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},U6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},rFa=function(a){this.o=a;
this.A=new I6},sFa=function(a){var b=V6(a.o,a.wl,"/mail/images/cleardot.gif");
l6(b);qFa(b.toString(),5E3,(0,g.B)(a.kK,a),3,2E3);a.Gf(1)},X6=function(a){var b=a.o.J;
if(null!=b)N6(5),b?(N6(11),W6(a.o,a,!1)):(N6(12),W6(a.o,a,!0));else if(a.Ie=new J6(a,void 0,void 0,void 0),a.Ie.Fi=a.Lt,b=a.o,b=V6(b,b.tn()?a.gm:null,a.Mt),N6(5),!g.Id||g.rc(10))m6(b,"TYPE","xmlhttp"),K6(a.Ie,b,!1,a.gm,!1);else{m6(b,"TYPE","html");var c=a.Ie;a=!!a.gm;c.Vj=3;c.yh=l6(b.clone());nFa(c,a)}},Y6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new I6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},tFa=function(a,b){this.o=a;
this.map=b;this.context=null},uFa=function(a){g.nf.call(this,"statevent",a)},vFa=function(a,b){g.nf.call(this,"timingevent",a);
this.size=b},wFa=function(a){g.nf.call(this,"serverreachability",a)},zFa=function(a){xFa(a);
if(3==a.o){var b=a.Zm++,c=a.Zo.clone();g.bn(c,"SID",a.B);g.bn(c,"RID",b);g.bn(c,"TYPE","terminate");Z6(a,c);b=new J6(a,a.B,b,void 0);b.Vj=2;b.yh=l6(c.clone());(new window.Image).src=b.yh;b.Sk=(0,g.H)();L6(b)}yFa(a)},AFa=function(a){a.IK(1,0);
a.Zo=V6(a,null,a.Kt);$6(a)},xFa=function(a){a.ph&&(a.ph.abort(),a.ph=null);
a.yc&&(a.yc.cancel(),a.yc=null);a.zg&&(g.x.clearTimeout(a.zg),a.zg=null);a7(a);a.ke&&(a.ke.cancel(),a.ke=null);a.sh&&(g.x.clearTimeout(a.sh),a.sh=null)},BFa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new tFa(a.wR++,b));2!=a.o&&3!=a.o||$6(a)},$6=function(a){a.ke||a.sh||(a.sh=S6((0,g.B)(a.HE,a),0),a.Lj=0)},DFa=function(a,b){if(1==a.o){if(!b){a.Zm=Math.floor(1E5*Math.random());
var c=a.Zm++,d=new J6(a,"",c,void 0);d.Fi=null;var e=b7(a),f=a.Zo.clone();g.bn(f,"RID",c);g.bn(f,"CVER","1");Z6(a,f);iFa(d,f,e);a.ke=d;a.o=2}}else 3==a.o&&(b?CFa(a,b):0==a.A.length||a.ke||CFa(a))},CFa=function(a,b){if(b)if(6<a.pi){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.Zm-1;var d=b7(a)}else c=b.G,d=b.hj;else c=a.Zm++,d=b7(a);var e=a.Zo.clone();g.bn(e,"SID",a.B);g.bn(e,"RID",c);g.bn(e,"AID",a.mk);Z6(a,e);c=new J6(a,a.B,c,a.Lj+1);c.Fi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ke=c;iFa(c,e,d)},Z6=function(a,b){if(a.Dd){var c=a.Dd.uA();
c&&g.Gb(c,function(a,c){g.bn(b,c,a)})}},b7=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.pi&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.pi?e:f-d;try{g.Gb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},EFa=function(a){a.yc||a.zg||(a.G=1,a.zg=S6((0,g.B)(a.GE,a),0),a.zj=0)},c7=function(a){if(a.yc||a.zg||3<=a.zj)return!1;
a.G++;a.zg=S6((0,g.B)(a.GE,a),FFa(a,a.zj));a.zj++;return!0},W6=function(a,b,c){a.vr=c;
a.Zf=b.Mg;a.F||AFa(a)},a7=function(a){null!=a.ri&&(g.x.clearTimeout(a.ri),a.ri=null)},FFa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},d7=function(a,b){if(2==b||9==b){var c=null;
a.Dd&&(c=null);var d=(0,g.B)(a.xX,a);c||(c=new g.Tm("//www.google.com/images/cleardot.gif"),l6(c));pFa(c.toString(),1E4,d)}else N6(2);GFa(a,b)},GFa=function(a,b){a.o=0;
a.Dd&&a.Dd.wz(b);yFa(a);xFa(a)},yFa=function(a){a.o=0;
a.Zf=-1;if(a.Dd)if(0==a.C.length&&0==a.A.length)a.Dd.Gs();else{g.Va(a.C);var b=g.Va(a.A);a.C.length=0;a.A.length=0;a.Dd.Gs(b)}},V6=function(a,b,c){var d=g.cn(c);
if(""!=d.A)b&&g.Vm(d,b+"."+d.A),g.Wm(d,d.D);else{var e=window.location;d=FEa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Ll&&g.Gb(a.Ll,function(a,b){g.bn(d,b,a)});
g.bn(d,"VER",a.pi);Z6(a,d);return d},S6=function(a,b){if(!g.ya(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},N6=function(a){e7.dispatchEvent(new uFa(e7,a))},HFa=function(){},IFa=function(a,b){this.action=a;
this.params=b||{}},f7=function(a,b){g.L.call(this);
this.o=new g.Bu(this.CV,0,this);g.M(this,this.o);this.Ed=5E3;this.A=0;if(g.ya(a))b&&(a=(0,g.B)(a,b));else if(a&&g.ya(a.handleEvent))a=(0,g.B)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},g7=function(a,b,c){this.L=a;
this.F=b;this.B=new g.zD;this.A=new f7(this.dY,this);this.o=this.ib=null;this.K=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.M=c||!1},JFa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.vr,sessionId:a.o.B,arrayId:a.o.mk}},KFa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&DFa(a.o),zFa(a.o));a.H=0},h7=function(a){return!!a.o&&3==a.o.o},LFa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},i7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Pg(a)||"";b&&(this.port=":"+b);this.domain=g.Og(a)||"";a=g.Eb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.xb(a,"10.0")&&(this.A=!1))},j7=function(a,b){var c=a.o;
if(g.u(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.Yg(c+b,{})},k7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ca(a.C,d,!0),onError:g.Ca(a.B,e),Id:g.Ca(a.D,e)};c&&(a.Ub=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.NE(b,a)},PFa=function(){var a=MFa;
NFa();l7.push(a);OFa(l7)},m7=function(a,b){NFa();
var c=l7,d=QFa(a,String(b));g.Na(c)?RFa(d):(OFa(c),(0,g.D)(c,function(a){a(d)}))},NFa=function(){l7||(l7=g.y("yt.mdx.remote.debug.handlers_")||[],g.ta("yt.mdx.remote.debug.handlers_",l7,void 0))},RFa=function(a){var b=(n7+1)%50;
n7=b;o7[b]=a;p7||(p7=49==b)},OFa=function(a){var b=o7;
if(b[0]){var c=n7,d=p7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.D)(a,function(a){a(e)})}while(d!=c);
o7=Array(50);n7=-1;p7=!1}},QFa=function(a,b){var c=((0,g.H)()-SFa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},q7=function(a){g.dG.call(this);
this.G=a;this.o=[]},TFa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},UFa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Xd)(a.o,function(a){return!!t6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=TFa(a,b[d])||c;return c},VFa=function(a,b){var c=a.o.length;
a.o=(0,g.Xd)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},r7=function(a,b,c,d){g.dG.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Ga=window.NaN},t7=function(a){q7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;s7(this);this.info("Initializing with "+r6(this.o))},WFa=function(a){if(a.o.length){var b=(0,g.J)(a.o,function(a){return a.id}),c=j7(a.B,"/pairing/get_lounge_token_batch");
k7(a.B,c,{screen_ids:b.join(",")},(0,g.B)(a.uL,a),(0,g.B)(a.tL,a))}},s7=function(a){var b=NEa(TEa());
b=(0,g.Xd)(b,function(a){return!a.uuid});
return UFa(a,b)},u7=function(a,b){VEa((0,g.J)(a.o,LEa));
b&&UEa()},w7=function(a,b){g.dG.call(this);
this.F=b;var c=g.BH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Ma(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;v7("Initialized with "+g.Gg(this.o))},XFa=function(a,b,c){var d=j7(a.D,"/pairing/get_screen_availability");
k7(a.D,d,{lounge_token:b.token},(0,g.B)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.B)(function(){c(!1)},a))},x7=function(a,b){a:if(g.Mb(b)!=g.Mb(a.o))var c=!1;
else{c=g.Pb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(v7("Updated online screens: "+g.Gg(a.o)),a.o=b,a.U("screenChange"));YFa(a)},y7=function(a){(0,window.isNaN)(a.B)||g.yE(a.B);
a.B=g.wE((0,g.B)(a.Gw,a),0<a.C&&a.C<(0,g.H)()?2E4:1E4)},v7=function(a){m7("OnlineScreenService",a)},ZFa=function(a){var b={};
(0,g.D)(a.F(),function(a){a.token?b[a.token]=a.id:this.sc("Requesting availability of screen w/o lounge token.")});
return b},YFa=function(a){a=g.Pb(g.Hb(a.o,function(a){return a}));
g.db(a);a.length?g.AH("yt-remote-online-screen-ids",a.join(","),60):g.CH("yt-remote-online-screen-ids")},z7=function(a){q7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};$Fa(this)},bGa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.De();if(k=(c?u6(k,c):null)||u6(k,b)){k.uuid=b;var l=A7(a,k);XFa(a.A,l,function(a){e(a?l:null)})}else c?aGa(a,c,(0,g.B)(function(a){var f=A7(this,new o6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));XFa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},cGa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},aGa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Ub:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.NE(j7(a.F,"/pairing/get_lounge_token_batch"),e)},dGa=function(a){a.o=a.B.De();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+r6(a.o))},$Fa=function(a){B7(a);
a.B=new t7(a.F);a.B.subscribe("screenChange",(0,g.B)(a.JL,a));dGa(a);a.C=NEa(g.BH("yt-remote-automatic-screen-cache")||[]);B7(a);a.info("Initializing automatic screens: "+r6(a.C));a.A=new w7(a.F,(0,g.B)(a.De,a,!0));a.A.subscribe("screenChange",(0,g.B)(function(){this.U("onlineScreenChange")},a))},A7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=u6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.AH("yt-remote-automatic-screen-cache",(0,g.J)(a.C,LEa)));B7(a);a.D[b.uuid]=b.id;g.AH("yt-remote-device-id-map",a.D,31536E3);return b},B7=function(a){a.D=g.BH("yt-remote-device-id-map")||{}},C7=function(a,b,c){g.dG.call(this);
this.M=c;this.J=a;this.A=b;this.B=null},D7=function(a,b){m7(a.M,b)},E7=function(a,b){C7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.B)(this.jY,this);this.D=(0,g.B)(this.oW,this);this.C=g.wE((0,g.B)(function(){eGa(this,null)},this),12E4)},fGa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Gg(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.A,(0,g.B)(function(){D7(this,"Failed to send message: getMdxSessionStatus.")},a)):D7(a,"Sending yt message without session: "+g.Gg(b))},eGa=function(a,b){g.yE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.B)(a.tq,a),d=(0,g.B)(a.He,a);a.EA(b,c,d,5)}}else a.He(Error("Waiting for session status timed out."))},F7=function(a,b,c){C7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.O=c;this.D=null;this.G=g.A;this.F=window.NaN;this.L=(0,g.B)(this.mY,this);this.o=g.A},gGa=function(a){a.o=a.J.eH(a.K,a.A.label,a.A.friendlyName,(0,g.B)(function(a){this.o=g.A;
this.tq(a)},a),(0,g.B)(function(a){this.o=g.A;
this.He(a)},a))},hGa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.O;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}XEa()&&(b.env_useStageMdx=1);return g.Wg(b)},G7=function(a,b){C7.call(this,a,b,"ManualSession");
this.o=g.wE((0,g.B)(this.pk,this,null),150)},H7=function(a,b,c,d){g.dG.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.B)(this.OU,this)},iGa=function(a,b){return b?g.Ha(a.B,function(a){return p6(b,a.label)},a):null},I7=function(a){m7("Controller",a)},MFa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},J7=function(a){return a.D||!!a.B.length||!!a.o},K7=function(a,b,c){b!=a.o&&(g.lf(a.o),(a.o=b)?(c?a.U("yt-remote-cast2-receiver-resumed",b.A):a.U("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.B)(a.EE,a,b)),b.B?a.U("yt-remote-cast2-session-change",b.B):c&&a.o.pk(null)):a.U("yt-remote-cast2-session-change",null))},jGa=function(a){var b=a.A.dH(),c=a.o&&a.o.A;
a=(0,g.J)(b,function(a){c&&p6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=iGa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},pGa=function(a,b,c,d,e,f,k){kGa()?lGa(b,e,f,k)&&(M7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?mGa(a,c):(window.__onGCastApiAvailable=function(b,d){b?mGa(a,c):(N7("Failed to load cast API: "+d),O7(!1),M7(!1),g.CH("yt-remote-cast-available"),g.CH("yt-remote-cast-receiver"),nGa(),
c(!1))},d?aFa():F6("CriOS")?fFa():F6("Android")&&F6("Chrome/")&&window.navigator.presentation?gFa():window.chrome&&window.navigator.presentation&&!F6("Edge")?(G6(),C6(oGa.map(dFa))):D6())):L7("Cannot initialize because not running Chrome")},nGa=function(){L7("dispose");
var a=P7();a&&a.dispose();g.ta("yt.mdx.remote.cloudview.instance_",null,void 0);qGa(!1);g.rG(Q7);Q7.length=0},R7=function(){return!!g.BH("yt-remote-cast-installed")},rGa=function(){var a=g.BH("yt-remote-cast-receiver");
return a?a.friendlyName:null},sGa=function(){L7("clearCurrentReceiver");
g.CH("yt-remote-cast-receiver")},tGa=function(){return R7()?P7()?P7().getCastSession():(N7("getCastSelector: Cast is not initialized."),null):(N7("getCastSelector: Cast API is not installed!"),null)},T7=function(){R7()?P7()?S7()?(L7("Requesting cast selector."),P7().requestSession()):(L7("Wait for cast API to be ready to request the session."),Q7.push(g.qG("yt-remote-cast2-api-ready",T7))):N7("requestCastSelector: Cast is not initialized."):N7("requestCastSelector: Cast API is not installed!")},U7=
function(a,b){S7()?P7().setConnectedScreenStatus(a,b):N7("setConnectedScreenStatus called before ready.")},kGa=function(){var a=0<=g.Eb.search(/ (CrMo|Chrome|CriOS)\//);
return g.QI||a},uGa=function(a,b){P7().init(a,b)},lGa=function(a,b,c,d){var e=!1;
P7()||(a=new H7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.AH("yt-remote-cast-available",a);g.uG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){L7("onReceiverSelected: "+a.friendlyName);
g.AH("yt-remote-cast-receiver",a);g.uG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){L7("onReceiverResumed: "+a.friendlyName);
g.AH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){L7("onSessionChange: "+q6(a));
a||g.CH("yt-remote-cast-receiver");g.uG("yt-remote-cast2-session-change",a)}),g.ta("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
L7("cloudview.createSingleton_: "+e);return e},P7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},mGa=function(a,b){O7(!0);
M7(!1);uGa(a,function(a){a?(qGa(!0),g.tG("yt-remote-cast2-api-ready")):(N7("Failed to initialize cast API."),O7(!1),g.CH("yt-remote-cast-available"),g.CH("yt-remote-cast-receiver"),nGa());b(a)})},L7=function(a){m7("cloudview",a)},N7=function(a){m7("cloudview",a)},O7=function(a){L7("setCastInstalled_ "+a);
g.AH("yt-remote-cast-installed",a)},S7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},qGa=function(a){L7("setApiReady_ "+a);
g.ta("yt.mdx.remote.cloudview.apiReady_",a,void 0)},M7=function(a){g.ta("yt.mdx.remote.cloudview.initializing_",a,void 0)},V7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.eg=!1;this.J=this.H=this.A=this.C=0;this.B=window.NaN;this.D=!1;this.reset(a)},W7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.eg=!1;a.hasNext=!1;a.G=0;a.F=(0,g.H)();a.C=0;a.A=0;a.H=0;a.J=0;a.B=window.NaN;a.D=!1},X7=function(a){return a.sb()?((0,g.H)()-a.F)/1E3:0},Y7=function(a,b){a.G=b;
a.F=(0,g.H)()},Z7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},$7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&W7(a)},a8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.o);b.hasPrevious=a.eg;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.A;b.duration=a.H;b.loadedTime=a.J;b.liveIngestionTime=a.B;return b},c8=function(a,b){g.dG.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.PC;this.B=this.A=null;this.J=(0,g.B)(this.gS,this);this.G=(0,g.B)(this.cn,this);this.H=(0,g.B)(this.fS,this);this.K=(0,g.B)(this.tS,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Nx,this),vGa(this))):c=3;0!=c&&(b?this.Nx(c):g.wE((0,g.B)(function(){this.Nx(c)},this),0));
var d=tGa();d&&b8(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},d8=function(a){return new V7(a.C.getPlayerContextData())},vGa=function(a){(0,g.D)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.Ca(this.JU,a),this))},a)},wGa=function(a){(0,g.D)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},e8=function(a,b){50>a.D.zc()&&g.RC(a.D,b)},g8=function(a,b,c){var d=d8(a);
Y7(d,c);-1E3!=d.playerState&&(d.playerState=b);f8(a,d)},h8=function(a,b,c){a.C.sendMessage(b,c)},f8=function(a,b){wGa(a);
a.C.setPlayerContextData(a8(b));vGa(a)},b8=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.cn(null));
a.B=b;a.B&&(m7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.cn(a.B.media[0]))},xGa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=d8(a);b.contentId!=d.videoId&&m7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;Y7(d,a.A.getEstimatedTime());f8(a,d)}else m7("CP","No cast media video. Ignoring state update.")},i8=function(a,b,c){return(0,g.B)(function(a){this.sc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.sc("Retrying "+b+" using MDx browser channel."),h8(this,b,c))},a)},j8=function(a,b,c){g.dG.call(this);
this.D=window.NaN;this.O=!1;this.K=this.J=this.L=this.M=window.NaN;this.V=[];this.C=this.G=this.B=this.jb=this.o=null;this.pa=a;this.V.push(g.NF(window,"beforeunload",(0,g.B)(this.lL,this)));this.A=[];this.jb=new V7;this.ba=b.id;this.o=yGa(this,c);this.o.subscribe("handlerOpened",this.kS,this);this.o.subscribe("handlerClosed",this.hS,this);this.o.subscribe("handlerError",this.iS,this);this.o.subscribe("handlerMessage",this.jS,this);LFa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.jb.videoId;g.DH()&&g.AH("yt-remote-session-video-id",a)},this)},k8=function(a){m7("conn",a)},yGa=function(a,b){return new g7(j7(a.pa,"/bc"),b)},l8=function(a,b){a.U("proxyStateChange",b)},zGa=function(a){a.D=g.wE((0,g.B)(function(){k8("Connecting timeout");
this.F(1)},a),2E4)},m8=function(a){g.yE(a.D);
a.D=window.NaN},n8=function(a){g.yE(a.M);
a.M=window.NaN},AGa=function(a){o8(a);
a.L=g.wE((0,g.B)(function(){p8(this,"getNowPlaying")},a),2E4)},o8=function(a){g.yE(a.L);
a.L=window.NaN},CGa=function(a,b){b&&(m8(a),n8(a));
b==(h7(a.o)&&(0,window.isNaN)(a.D))?b&&(l8(a,1),p8(a,"getSubtitlesTrack")):b?(a.Z()&&a.jb.reset(),l8(a,1),p8(a,"getNowPlaying"),BGa(a)):a.F(1)},DGa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.jb.videoId&&(g.Xb(b.params)?a.jb.o=null:a.jb.o=b.params,a.U("remotePlayerChange"))},EGa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.jb.listId=b.params.listId||a.jb.listId;$7(a.jb,c,d);a.U("remoteQueueChange")},GGa=function(a,b){b.params=b.params||{};
EGa(a,b);FGa(a,b);a.U("autoplayDismissed")},FGa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
Y7(a.jb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.jb.playerState&&(c=-1E3);a.jb.playerState=c;c=Number(b.params.loadedTime);a.jb.J=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.jb.H=(0,window.isNaN)(c)?0:c;c=a.jb;var d=Number(b.params.liveIngestionTime);c.B=d;c.D=(0,window.isNaN)(d)?!1:!0;c=a.jb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=(0,window.isNaN)(d)?0:d;c.A=(0,window.isNaN)(e)?0:
e;1==a.jb.playerState?AGa(a):o8(a);a.U("remotePlayerChange")},HGa=function(a,b){if(-1E3!=a.jb.playerState){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.jb.playerState=c;c=(0,window.parseInt)(b.params.currentTime,10);Y7(a.jb,(0,window.isNaN)(c)?0:c);a.U("remotePlayerChange")}},IGa=function(a,b){var c="true"==b.params.muted;
a.jb.volume=(0,window.parseInt)(b.params.volume,10);a.jb.muted=c;a.U("remotePlayerChange")},JGa=function(a,b){a.G=b.params.videoId;
a.U("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},KGa=function(a,b){var c="true"==b.params.hasNext;
a.jb.eg="true"==b.params.hasPrevious;a.jb.hasNext=c;a.U("previousNextChange")},BGa=function(a){g.yE(a.K);
a.K=g.wE((0,g.B)(a.F,a,1),864E5)},p8=function(a,b,c){c?k8("Sending: action="+b+", params="+g.Gg(c)):k8("Sending: action="+b);
a.o.sendMessage(b,c)},q8=function(a){q7.call(this,"ScreenServiceProxy");
this.nd=a;this.A=[];this.A.push(this.nd.$_s("screenChange",(0,g.B)(this.hY,this)));this.A.push(this.nd.$_s("onlineScreenChange",(0,g.B)(this.iU,this)))},PGa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.lE("MDX_CONFIG")||b;PEa();y6();r8||(r8=new i7(b?b.loungeApiHost:void 0),XEa()&&(r8.o="/api/loungedev"));s8||(s8=g.y("yt.mdx.remote.deferredProxies_")||[],g.ta("yt.mdx.remote.deferredProxies_",s8,void 0));LGa();var c=t8();if(!c){var d=new z7(r8);g.ta("yt.mdx.remote.screenService_",d,void 0);c=t8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);pGa(a,d,function(a){a?u8()&&U7(u8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.uG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.ta("yt.mdx.remote.initialized_",!0,void 0),v8("Initializing: "+g.Gg(b)),w8.push(g.qG("yt-remote-cast2-availability-change",function(){g.uG("yt-remote-receiver-availability-change")})),w8.push(g.qG("yt-remote-cast2-receiver-selected",function(){x8(null);
g.uG("yt-remote-auto-connect","cast-selector-receiver")})),w8.push(g.qG("yt-remote-cast2-receiver-resumed",function(){g.uG("yt-remote-receiver-resumed","cast-selector-receiver")})),w8.push(g.qG("yt-remote-cast2-session-change",MGa)),w8.push(g.qG("yt-remote-connection-change",function(a){a?U7(u8(),"YouTube TV"):y8()||(U7(null,null),sGa())})),a=z8(),b.isAuto&&(a.id+="#dial"),g.tE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),v8(" -- with channel params: "+
g.Gg(a)),NGa(a),c.start(),u8()||OGa())},RGa=function(){var a=QGa();
R7()&&g.BH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},QGa=function(){var a=t8().nd.$_gos();
var b=A8();b&&B8()&&(t6(a,b)||a.push(b));return OEa(a)},C8=function(){var a=SGa();
!a&&R7()&&rGa()&&(a={key:"cast-selector-receiver",name:rGa()});return a},SGa=function(){var a=QGa(),b=A8();
b||(b=y8());return g.Ha(a,function(a){return b&&p6(b,a.key)?!0:!1})},A8=function(){var a=u8();
if(!a)return null;var b=t8().De();return u6(b,a)},MGa=function(a){v8("remote.onCastSessionChange_: "+q6(a));
if(a){var b=A8();b&&b.id==a.id?U7(b.id,"YouTube TV"):(b&&D8(),E8(a,1))}else B8()&&D8()},D8=function(){S7()?P7().stopSession():N7("stopSession called before API ready.");
var a=B8();a&&(a.disconnect(1),F8(null))},G8=function(){var a=B8();
return!!a&&3!=a.getProxyState()},v8=function(a){m7("remote",a)},t8=function(){if(!H8){var a=g.y("yt.mdx.remote.screenService_");
H8=a?new q8(a):null}return H8},u8=function(){return g.y("yt.mdx.remote.currentScreenId_")},TGa=function(a){g.ta("yt.mdx.remote.currentScreenId_",a,void 0)},UGa=function(){return g.y("yt.mdx.remote.connectData_")},x8=function(a){g.ta("yt.mdx.remote.connectData_",a,void 0)},B8=function(){return g.y("yt.mdx.remote.connection_")},F8=function(a){var b=B8();
x8(null);a||TGa("");g.ta("yt.mdx.remote.connection_",a,void 0);s8&&((0,g.D)(s8,function(b){b(a)}),s8.length=0);
b&&!a?g.uG("yt-remote-connection-change",!1):!b&&a&&g.uG("yt-remote-connection-change",!0)},y8=function(){var a=g.DH();
if(!a)return null;var b=t8().De();return u6(b,a)},E8=function(a,b){A8()&&A8();
TGa(a.id);var c=new j8(r8,a,z8());c.connect(b,UGa());c.subscribe("beforeDisconnect",function(a){g.uG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){B8()&&F8(null)});
F8(c)},OGa=function(){var a=y8();
a?(v8("Resume connection to: "+q6(a)),E8(a,0)):(z6(),sGa(),v8("Skipping connecting because no session screen found."))},LGa=function(){var a=z8();
if(g.Xb(a)){a=x6();var b=g.BH("yt-remote-session-name")||"",c=g.BH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ta("yt.mdx.remote.channelParams_",a,void 0)}},z8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},NGa=function(a){a?(g.AH("yt-remote-session-app",a.app),g.AH("yt-remote-session-name",a.name)):(g.CH("yt-remote-session-app"),g.CH("yt-remote-session-name"));
g.ta("yt.mdx.remote.channelParams_",a,void 0)},I8=function(a,b,c){g.L.call(this);
this.D=a;this.A=b;this.B=new g.aG(this);g.M(this,this.B);this.B.R(b,"onCaptionsTrackListChanged",this.zT);this.B.R(b,"captionschanged",this.eS);this.B.R(b,"captionssettingschanged",this.kG);this.B.R(b,"videoplayerreset",this.uq);this.B.R(b,"mdxautoplaycancel",this.jK);this.V=this.B.R(b,"onVolumeChange",this.mE);this.H=!1;this.o=c;c.subscribe("proxyStateChange",this.AE,this);c.subscribe("remotePlayerChange",this.fn,this);c.subscribe("remoteQueueChange",this.uq,this);c.subscribe("autoplayUpNext",this.YD,
this);c.subscribe("previousNextChange",this.xE,this);c.subscribe("nowAutoplaying",this.pE,this);c.subscribe("autoplayDismissed",this.XD,this);this.suggestion=null;this.J=new g.zP(64);this.C=new g.Bu(this.gG,500,this);g.M(this,this.C);this.F=new g.Bu(this.hG,1E3,this);g.M(this,this.F);this.L=new H6(this.IX,0,this);g.M(this,this.L);this.G={};this.M=new g.Bu(this.KG,1E3,this);g.M(this,this.M);this.K=new g.ul(this.gQ,1E3,this);g.M(this,this.K);this.O=g.A;this.kG();this.uq();this.fn()},J8=function(a,b){var c=
a.D,d=a.A.getVideoData().lengthSeconds;
c.J=b||0;c.player.U("progresssync",b,d)},VGa=function(a){J8(a,0);
a.C.stop();K8(a,new g.zP(64))},M8=function(a,b){if(L8(a)&&!a.H){var c=null;
b&&(c={style:a.A.Yi()},g.ec(c,b));a.o.UF(a.A.getVideoData(1).videoId,c);a.G=d8(a.o).o}},N8=function(a,b){var c=a.A.mg();
if(c){var d=c.Be();var e=c.listId.toString()}var f=a.A.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.ek;f=EEa(f);var n=d8(c);l=l||0;var p={videoId:k,currentIndex:l};$7(n,k,l);g.u(b)&&(Y7(n,b),p.currentTime=b);g.u(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Gg(f));h8(c,"setPlaylist",p);e||f8(c,n);K8(a,new g.zP(1))},WGa=function(a,b){if(b){var c=a.A.Cc("captions","tracklist",{wB:1});
c&&c.length?(a.A.Xd("captions","track",b),a.H=!1):(a.A.xk("captions"),a.H=!0)}else a.A.Xd("captions","track",{})},L8=function(a){return d8(a.o).videoId==a.A.getVideoData(1).videoId},K8=function(a,b){a.F.stop();
var c=a.J;if(!g.FP(c,b)){var d=g.W(b,2);d!=g.W(a.J,2)&&g.TT(a.A,d);a.J=b;XGa(a.D,c,b)}},O8=function(a){g.V.call(this,{I:"div",
N:"ytp-remote",P:[{I:"div",N:"ytp-remote-display-status",P:[{I:"div",N:"ytp-remote-display-status-icon",P:[g.Xra()]},{I:"div",N:"ytp-remote-display-status-text",ca:"{{statustext}}"}]}]});this.B=new g.RU(this,250);g.M(this,this.B);this.C=a;this.R(a,"presentingplayerstatechange",this.D);YGa(this,g.PT(a))},YGa=function(a,b){if(3==a.C.Ta()){var c={RECEIVER_NAME:a.C.Cc("remote","currentReceiver").name};
c=g.W(b,128)?g.JU("Erro em $RECEIVER_NAME",c):b.sb()||g.W(b,4)?g.JU("Reproduzindo em $RECEIVER_NAME",c):g.JU("Conectado a $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},P8=function(a,b){g.rY.call(this,"Reproduzir em",0,a,b);
this.B=a;this.J={};this.R(a,"onMdxReceiversChange",this.L);this.R(a,"presentingplayerstatechange",this.L);this.L()},Q8=function(a){g.sU.call(this,a);
this.A={key:s6(),name:"Este computador"};this.C=null;this.D=[];this.K=this.o=null;this.H=[this.A];this.B=this.A;this.F=new g.zP(64);this.J=0;this.G=-1;if(!g.qN(g.X(this.player))){a=this.player;var b=g.rI(a);b&&(b=b.Tm())&&(b=new P8(a,b),g.M(this,b));b=new O8(a);g.M(this,b);g.iU(a,b.element,4)}},XGa=function(a,b,c){a.F=c;
a.player.U("presentingplayerstatechange",new g.KP(c,b))},R8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)D8();
else{a.B=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.mg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Qa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.ek,index:Math.max(a.player.BC(),0),currentTime:0==f?void 0:f};(d=EEa(d))&&(c.locationInfo=d);d=c}else d=null;v8("Connecting to: "+g.Gg(b));"cast-selector-receiver"==b.key?(x8(d||null),S7()?P7().setLaunchParams(d||
null):N7("setLaunchParams called before ready.")):!d&&G8()&&u8()==b.key?g.uG("yt-remote-connection-change",!0):(D8(),x8(d||null),d=t8().De(),(d=u6(d,b.key))&&E8(d,1))}},mFa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},R6={"'":"\\'"},ZGa={},KEa={HZ:"atp",l4:"ska",C3:"que",P2:"mus",g4:"sus",T0:"dsp"};
n6.prototype.Ho=function(){var a=new n6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var A6,w6="",E6=B6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",eFa=B6("loadCastFramework")||B6("loadCastApplicationFramework"),oGa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.C(H6,g.L);g.h=H6.prototype;g.h.gL=function(a){this.C=arguments;this.o=!1;this.Ga?this.B=(0,g.H)()+this.Ed:this.Ga=g.Bg(this.D,this.Ed)};
g.h.stop=function(){this.Ga&&(g.Cg(this.Ga),this.Ga=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.X=function(){this.stop();H6.fa.X.call(this)};
g.h.hL=function(){this.B?(this.Ga=g.Bg(this.D,this.B-(0,g.H)()),this.B=null):(this.Ga=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};I6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
I6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=J6.prototype;g.h.Fi=null;g.h.Nf=!1;g.h.ol=null;g.h.Fx=null;g.h.Sk=null;g.h.Vj=null;g.h.yh=null;g.h.Yh=null;g.h.hj=null;g.h.Wc=null;g.h.Cn=0;g.h.Of=null;g.h.xr=null;g.h.zh=null;g.h.hm=-1;g.h.AF=!0;g.h.ni=!1;g.h.Nt=0;g.h.Jq=null;var kFa={},M6={};g.h=J6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.IW=function(a){a=a.target;var b=this.Jq;b&&3==g.Jx(a)?b.Zl():this.WG(a)};
g.h.WG=function(a){try{if(a==this.Wc)a:{var b=g.Jx(this.Wc),c=this.Wc.A,d=this.Wc.getStatus();if(g.Id&&!g.rc(10)||g.Kd&&!g.qc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.pf&&!g.Nx(this.Wc))break a;this.ni||4!=b||7==c||(8==c||0>=d?this.o.Gf(3):this.o.Gf(2));T6(this);var e=this.Wc.getStatus();this.hm=e;var f=g.Nx(this.Wc);(this.Nf=200==e)?(4==b&&P6(this),this.D?(lFa(this,b,f),g.pf&&this.Nf&&3==b&&(this.Y.W(this.A,"tick",this.FW),this.A.start())):O6(this,f),this.Nf&&!this.ni&&(4==b?this.o.rq(this):
(this.Nf=!1,L6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.zh=3,N6(13)):(this.zh=0,N6(14)),P6(this),Q6(this))}}catch(k){this.Wc&&g.Nx(this.Wc)}finally{}};
g.h.FW=function(){var a=g.Jx(this.Wc),b=g.Nx(this.Wc);this.Cn<b.length&&(T6(this),lFa(this,a,b),this.Nf&&4!=a&&L6(this))};
g.h.MV=function(a){S6((0,g.B)(this.LV,this,a),0)};
g.h.LV=function(a){this.ni||(T6(this),O6(this,a),L6(this))};
g.h.JE=function(a){S6((0,g.B)(this.KV,this,a),0)};
g.h.KV=function(a){this.ni||(P6(this),this.Nf=a,this.o.rq(this),this.o.Gf(4))};
g.h.cancel=function(){this.ni=!0;P6(this)};
g.h.cW=function(){this.ol=null;var a=(0,g.H)();0<=a-this.Fx?(2!=this.Vj&&this.o.Gf(3),P6(this),this.zh=2,N6(18),Q6(this)):oFa(this,this.Fx-a)};g.h=rFa.prototype;g.h.Lt=null;g.h.Ie=null;g.h.Kq=!1;g.h.PA=null;g.h.Vo=null;g.h.Eu=null;g.h.Mt=null;g.h.af=null;g.h.Mg=-1;g.h.gm=null;g.h.wl=null;g.h.connect=function(a){this.Mt=a;a=V6(this.o,null,this.Mt);N6(3);this.PA=(0,g.H)();var b=this.o.H;null!=b?(this.gm=b[0],(this.wl=b[1])?(this.af=1,sFa(this)):(this.af=2,X6(this))):(m6(a,"MODE","init"),this.Ie=new J6(this,void 0,void 0,void 0),this.Ie.Fi=this.Lt,K6(this.Ie,a,!1,null,!0),this.af=0)};
g.h.kK=function(a){if(a)this.af=2,X6(this);else{N6(4);var b=this.o;b.Zf=b.ph.Mg;d7(b,9)}a&&this.Gf(2)};
g.h.Vs=function(a){return this.o.Vs(a)};
g.h.abort=function(){this.Ie&&(this.Ie.cancel(),this.Ie=null);this.Mg=-1};
g.h.OA=function(){return!1};
g.h.BE=function(a,b){this.Mg=a.hm;if(0==this.af)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Zf=this.Mg;d7(c,2);return}this.gm=c[0];this.wl=c[1]}else c=this.o,c.Zf=this.Mg,d7(c,2);else if(2==this.af)if(this.Kq)N6(7),this.Eu=(0,g.H)();else if("11111"==b){if(N6(6),this.Kq=!0,this.Vo=(0,g.H)(),c=this.Vo-this.PA,!g.Id||g.rc(10)||500>c)this.Mg=200,this.Ie.cancel(),N6(12),W6(this.o,this,!0)}else N6(8),this.Vo=this.Eu=(0,g.H)(),this.Kq=!1};
g.h.rq=function(){this.Mg=this.Ie.hm;if(this.Ie.Nf)0==this.af?this.wl?(this.af=1,sFa(this)):(this.af=2,X6(this)):2==this.af&&((!g.Id||g.rc(10)?!this.Kq:200>this.Eu-this.Vo)?(N6(11),W6(this.o,this,!1)):(N6(12),W6(this.o,this,!0)));else{0==this.af?N6(9):2==this.af&&N6(10);var a=this.o;a.Zf=this.Mg;d7(a,2)}};
g.h.tn=function(){return this.o.tn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Gf=function(a){this.o.Gf(a)};g.h=Y6.prototype;g.h.Ll=null;g.h.ke=null;g.h.yc=null;g.h.Kt=null;g.h.Zo=null;g.h.kz=null;g.h.pp=null;g.h.Zm=0;g.h.wR=0;g.h.Dd=null;g.h.sh=null;g.h.zg=null;g.h.ri=null;g.h.ph=null;g.h.vr=null;g.h.mk=-1;g.h.KB=-1;g.h.Zf=-1;g.h.Lj=0;g.h.zj=0;g.h.pi=8;var e7=new g.Pf;g.C(uFa,g.nf);g.C(vFa,g.nf);g.C(wFa,g.nf);g.h=Y6.prototype;g.h.connect=function(a,b,c,d,e){N6(0);this.Kt=b;this.Ll=c||{};d&&g.u(e)&&(this.Ll.OSID=d,this.Ll.OAID=e);this.F?(S6((0,g.B)(this.Gz,this,a),100),AFa(this)):this.Gz(a)};
g.h.Gz=function(a){this.ph=new rFa(this);this.ph.Lt=null;this.ph.A=this.D;this.ph.connect(a)};
g.h.OA=function(){return 0==this.o};
g.h.HE=function(a){this.sh=null;DFa(this,a)};
g.h.GE=function(){this.zg=null;this.yc=new J6(this,this.B,"rpc",this.G);this.yc.Fi=null;this.yc.Nt=0;var a=this.kz.clone();g.bn(a,"RID","rpc");g.bn(a,"SID",this.B);g.bn(a,"CI",this.vr?"0":"1");g.bn(a,"AID",this.mk);Z6(this,a);if(!g.Id||g.rc(10))g.bn(a,"TYPE","xmlhttp"),K6(this.yc,a,!0,this.pp,!1);else{g.bn(a,"TYPE","html");var b=this.yc,c=!!this.pp;b.Vj=3;b.yh=l6(a.clone());nFa(b,c)}};
g.h.BE=function(a,b){if(0!=this.o&&(this.yc==a||this.ke==a))if(this.Zf=a.hm,this.ke==a&&3==this.o)if(7<this.pi){try{var c=this.D.parse(b)}catch(f){c=null}if(g.wa(c)&&3==c.length)if(0==c[0])a:{if(!this.zg){if(this.yc)if(this.yc.Sk+3E3<this.ke.Sk)a7(this),this.yc.cancel(),this.yc=null;else break a;c7(this);N6(19)}}else this.KB=c[1],0<this.KB-this.mk&&37500>c[2]&&this.vr&&0==this.zj&&!this.ri&&(this.ri=S6((0,g.B)(this.ZR,this),6E3));else d7(this,11)}else b!=ZGa.J_.o&&d7(this,11);else if(this.yc==a&&
a7(this),!g.F(b)){c=this.D.parse(b);g.wa(c);for(var d=0;d<c.length;d++){var e=c[d];this.mk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.pp=e[2],e=e[3],null!=e?this.pi=e:this.pi=6,this.o=3,this.Dd&&this.Dd.yz(),this.kz=V6(this,this.tn()?this.pp:null,this.Kt),EFa(this)):"stop"==e[0]&&d7(this,7):3==this.o&&("stop"==e[0]?d7(this,7):"noop"!=e[0]&&this.Dd&&this.Dd.xz(e),this.zj=0)}}};
g.h.ZR=function(){null!=this.ri&&(this.ri=null,this.yc.cancel(),this.yc=null,c7(this),N6(20))};
g.h.rq=function(a){if(this.yc==a){a7(this);this.yc=null;var b=2}else if(this.ke==a)this.ke=null,b=1;else return;this.Zf=a.hm;if(0!=this.o)if(a.Nf)1==b?(b=(0,g.H)()-a.Sk,e7.dispatchEvent(new vFa(e7,a.hj?a.hj.length:0,b,this.Lj)),$6(this),this.C.length=0):EFa(this);else{var c=a.zh,d;if(!(d=3==c||7==c||0==c&&0<this.Zf)){if(d=1==b)this.ke||this.sh||1==this.o||2<=this.Lj?d=!1:(this.sh=S6((0,g.B)(this.HE,this,a),FFa(this,this.Lj)),this.Lj++,d=!0);d=!(d||2==b&&c7(this))}if(d)switch(c){case 1:d7(this,5);
break;case 4:d7(this,10);break;case 3:d7(this,6);break;case 7:d7(this,12);break;default:d7(this,2)}}};
g.h.IK=function(a){if(!g.Ma(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.xX=function(a){a?N6(2):(N6(1),GFa(this,8))};
g.h.Vs=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Dx;a.H=!1;return a};
g.h.isActive=function(){return!!this.Dd&&this.Dd.isActive(this)};
g.h.Gf=function(a){e7.dispatchEvent(new wFa(e7,a))};
g.h.tn=function(){return!(!g.Id||g.rc(10))};
g.h=HFa.prototype;g.h.yz=function(){};
g.h.xz=function(){};
g.h.wz=function(){};
g.h.Gs=function(){};
g.h.uA=function(){return{}};
g.h.isActive=function(){return!0};g.C(f7,g.L);g.h=f7.prototype;g.h.CV=function(){this.Ed=Math.min(3E5,2*this.Ed);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Ed+15E3*Math.random();g.Cu(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Ed=5E3};g.C(g7,HFa);g.h=g7.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.de=function(a){return this.B.de(a)};
g.h.U=function(a,b){return this.B.U.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.lf(this.B),KFa(this),g.lf(this.A),this.A=null)};
g.h.la=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new Y6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.o;e&&(e.Dd=null);d.Dd=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.mk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):h7(this)&&BFa(this.o,c)};
g.h.yz=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)BFa(this.o,a[b])}this.U("handlerOpened")};
g.h.wz=function(a){var b=2==a&&401==this.o.Zf;4==a||b||this.A.start();this.U("handlerError",a)};
g.h.Gs=function(a){if(!this.A.isActive())this.U("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.uA=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.ec(a,this.D);return a};
g.h.xz=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),zFa(this.o)):this.U("handlerMessage",new IFa(a[0],a[1]))};
g.h.dY=function(){this.A.isActive();var a=this.o,b=0;a.yc&&b++;a.ke&&b++;0!=b||this.connect(this.D,this.C)};i7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
i7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
i7.prototype.D=function(a){a(Error("request timed out"))};var SFa=(0,g.H)(),l7=null,o7=Array(50),n7=-1,p7=!1;g.C(q7,g.dG);q7.prototype.De=function(){return this.o};
q7.prototype.contains=function(a){return!!t6(this.o,a)};
q7.prototype.get=function(a){return a?u6(this.o,a):null};
q7.prototype.info=function(a){m7(this.G,a)};g.C(r7,g.dG);var $Ga=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=r7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Ga)&&this.cH()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Ga)||(g.yE(this.Ga),this.Ga=window.NaN)};
g.h.X=function(){this.stop();r7.fa.X.call(this)};
g.h.cH=function(){this.Ga=window.NaN;this.o=g.NE(j7(this.F,"/pairing/get_screen"),{method:"POST",Ub:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.B)(this.fY,this),onError:(0,g.B)(this.eY,this),Id:(0,g.B)(this.gY,this)})};
g.h.fY=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.U("pairingComplete",new o6(c))};
g.h.eY=function(a){this.o=null;a.status&&404==a.status?this.A>=$Ga.length?this.U("pairingFailed",Error("DIAL polling timed out")):(a=$Ga[this.A],this.Ga=g.wE((0,g.B)(this.cH,this),a),this.A++):this.U("pairingFailed",Error("Server error "+a.status))};
g.h.gY=function(){this.o=null;this.U("pairingFailed",Error("Server not responding"))};g.C(t7,q7);g.h=t7.prototype;g.h.start=function(){s7(this)&&this.U("screenChange");!g.BH("yt-remote-lounge-token-expiration")&&WFa(this);g.yE(this.A);this.A=g.wE((0,g.B)(this.start,this),1E4)};
g.h.add=function(a,b){s7(this);TFa(this,a);u7(this,!1);this.U("screenChange");b(a);a.token||WFa(this)};
g.h.remove=function(a,b){var c=s7(this);VFa(this,a)&&(u7(this,!1),c=!0);b(a);c&&this.U("screenChange")};
g.h.rr=function(a,b,c,d){var e=s7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,u7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.U("screenChange")};
g.h.X=function(){g.yE(this.A);t7.fa.X.call(this)};
g.h.uL=function(a){s7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}u7(this,!b);b&&m7(this.G,"Missed "+b+" lounge tokens.")};
g.h.tL=function(a){m7(this.G,"Requesting lounge tokens failed: "+a)};g.C(w7,g.dG);g.h=w7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.BH("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.H)()-144E5<a?0:a)?y7(this):(this.C=(0,g.H)()+3E5,g.AH("yt-remote-fast-check-period",this.C),this.Gw())};
g.h.isEmpty=function(){return g.Xb(this.o)};
g.h.update=function(){v7("Updating availability on schedule.");var a=this.F(),b=g.Hb(this.o,function(b,d){return b&&!!u6(a,d)},this);
x7(this,b)};
g.h.X=function(){g.yE(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);w7.fa.X.call(this)};
g.h.Gw=function(){g.yE(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=ZFa(this);if(g.Mb(a)){var b=j7(this.D,"/pairing/get_screen_availability");this.A=k7(this.D,b,{lounge_token:g.Pb(a).join(",")},(0,g.B)(this.kV,this,a),(0,g.B)(this.jV,this))}else x7(this,{}),y7(this)};
g.h.kV=function(a,b){this.A=null;var c=g.Pb(ZFa(this));if(g.eb(c,g.Pb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;x7(this,d);y7(this)}else this.sc("Changing Screen set during request."),this.Gw()};
g.h.jV=function(a){this.sc("Screen availability failed: "+a);this.A=null;y7(this)};
g.h.sc=function(a){m7("OnlineScreenService",a)};g.C(z7,q7);g.h=z7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.U("screenChange"),this.A.isEmpty()||this.U("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.rr=function(a,b,c,d){this.B.contains(a)?this.B.rr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,m7(this.G,a),d(Error(a)))};
g.h.De=function(a){return a?this.o:g.Ua(this.o,(0,g.Xd)(this.C,function(a){return!this.contains(a)},this))};
g.h.dH=function(){return(0,g.Xd)(this.De(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.eH=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new r7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.B)(function(a){g.lf(f);d(A7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.lf(f);e(a)});
f.start();return(0,g.B)(f.stop,f)};
g.h.iY=function(a,b,c,d){g.NE(j7(this.F,"/pairing/get_screen"),{method:"POST",Ub:{pairing_code:a},timeout:5E3,onSuccess:(0,g.B)(function(a,d){var e=new o6(d.screen||{});if(!e.name||cGa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);cGa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(A7(this,e))},this),
onError:(0,g.B)(function(a){d(Error("pairing request failed: "+a.status))},this),
Id:(0,g.B)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.lf(this.B);g.lf(this.A);z7.fa.X.call(this)};
g.h.JL=function(){dGa(this);this.U("screenChange");this.A.update()};
z7.prototype.dispose=z7.prototype.dispose;g.C(C7,g.dG);g.h=C7.prototype;g.h.tq=function(a){this.B=a;this.U("sessionScreen",this.B)};
g.h.He=function(a){this.la()||(a&&D7(this,""+a),this.B=null,this.U("sessionScreen",null))};
g.h.info=function(a){m7(this.M,a)};
g.h.gH=function(){return null};
g.h.Pw=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.B)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.B)(function(){D7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.Pw("");C7.fa.X.call(this)};g.C(E7,C7);g.h=E7.prototype;g.h.Ow=function(a){if(this.o){if(this.o==a)return;D7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);fGa(this)};
g.h.pk=function(a){this.info("launchWithParams no-op for Cast: "+g.Gg(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.B)(function(){this.He()},this),(0,g.B)(function(){this.He(Error("Failed to stop receiver app."))},this)):this.He(Error("Stopping cast device witout session."))};
g.h.Pw=g.A;g.h.X=function(){this.info("disposeInternal");g.yE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;E7.fa.X.call(this)};
g.h.oW=function(a,b){if(!this.la())if(b){var c=g.xx(b);if(g.za(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Gg(c));switch(d){case "mdxSessionStatus":eGa(this,c.screenId);break;default:D7(this,"Unknown youtube message: "+d)}}else D7(this,"Unable to parse message.")}else D7(this,"No data in message.")};
g.h.EA=function(a,b,c,d){bGa(this.J,this.A.label,a,this.A.friendlyName,(0,g.B)(function(e){e?b(e):0<=d?(D7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.wE((0,g.B)(this.EA,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.gH=function(){return this.o};
g.h.jY=function(a){this.la()||a||(D7(this,"Cast session died."),this.He())};g.C(F7,C7);g.h=F7.prototype;g.h.Ow=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.pk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.A;g.yE(this.F);this.C?this.C.stop((0,g.B)(this.He,this,null),(0,g.B)(this.He,this,"Failed to stop DIAL device.")):this.He()};
g.h.X=function(){this.o();this.o=g.A;g.yE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;F7.fa.X.call(this)};
g.h.mY=function(a){this.la()||a||(D7(this,"DIAL session died."),this.o(),this.o=g.A,this.He())};
g.h.pu=function(a){this.K=s6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,hGa(this));a(b);gGa(this)}else this.G=(0,g.B)(function(){g.yE(this.F);this.G=g.A;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,hGa(this));a(b);gGa(this)},this),this.F=g.wE((0,g.B)(function(){this.G()},this),100)};
g.h.XM=function(a,b,c){bGa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.B)(function(a){a&&a.token?(this.tq(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.pu(b,c)},this),(0,g.B)(function(a){D7(this,"Failed to get DIAL screen: "+a);
this.pu(b,c)},this))};g.C(G7,C7);G7.prototype.stop=function(){this.He()};
G7.prototype.Ow=g.A;G7.prototype.pk=function(){g.yE(this.o);this.o=window.NaN;var a=u6(this.J.De(),this.A.label);a?this.tq(a):this.He(Error("No such screen"))};
G7.prototype.X=function(){g.yE(this.o);this.o=window.NaN;G7.fa.X.call(this)};g.C(H7,g.dG);g.h=H7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.B)(this.DE,this),(0,g.B)(this.SU,this),d,e);c.customDialLaunchCallback=(0,g.B)(this.JS,this);window.chrome.cast.initialize(c,
(0,g.B)(function(){this.la()||(window.chrome.cast.addReceiverActionListener(this.C),PFa(),this.A.subscribe("onlineScreenChange",(0,g.B)(this.fH,this)),this.B=jGa(this),window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(a){this.sc("Failed to set initial custom receivers: "+g.Gg(a))},this)),this.U("yt-remote-cast2-availability-change",J7(this)),b(!0))},this),(0,g.B)(function(a){this.sc("Failed to initialize API: "+g.Gg(a));
b(!1)},this))};
g.h.gX=function(a,b){I7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)I7("Unsetting old screen status: "+this.o.A.friendlyName),K7(this,null)}if(a&&b){if(!this.o){c=u6(this.A.De(),a);if(!c){I7("setConnectedScreenStatus: Unknown screen.");return}var d=iGa(this,c);d||(I7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(a){this.sc("Failed to set initial custom receivers: "+g.Gg(a))},this)));
I7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);K7(this,new G7(this.A,d),!0)}this.o.Pw(b)}else I7("setConnectedScreenStatus: no screen.")};
g.h.hX=function(a){this.la()?this.sc("Setting connection data on disposed cast v2"):this.o?this.o.pk(a):this.sc("Setting connection data without a session")};
g.h.lY=function(){this.la()?this.sc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),K7(this,null)):I7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.B)(this.DE,this),(0,g.B)(this.oV,this))};
g.h.X=function(){this.A.unsubscribe("onlineScreenChange",(0,g.B)(this.fH,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.Sa(g.y("yt.mdx.remote.debug.handlers_")||[],MFa);g.lf(this.o);H7.fa.X.call(this)};
g.h.sc=function(a){m7("Controller",a)};
g.h.EE=function(a,b){this.o==a&&(b||K7(this,null),this.U("yt-remote-cast2-session-change",b))};
g.h.OU=function(a,b){if(!this.la())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),I7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)I7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{I7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.U("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:K7(this,
new G7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:K7(this,new F7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:K7(this,new E7(this.A,a));break;default:this.sc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.sc("Stopping receiver w/o session: "+a.friendlyName)}else this.sc("onReceiverAction_ called without receiver.")};
g.h.JS=function(a){if(this.la())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.sc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.sc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return I7("Reselecting dial screen."),
this.U("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.sc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);K7(this,new F7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.B)(b.XM,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.B)(b.pu,b))};
g.h.DE=function(a){if(!this.la()){I7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)I7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),K7(this,new E7(this.A,b),!0);else{this.sc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=u6(this.A.De(),c.label);
d&&p6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(I7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.lf(this.o),this.o=new E7(this.A,b),this.o.subscribe("sessionScreen",(0,g.B)(this.EE,this,this.o)),this.o.pk(null));this.o.Ow(a)}}};
g.h.kY=function(){return this.o?this.o.gH():null};
g.h.oV=function(a){this.la()||(this.sc("Failed to estabilish a session: "+g.Gg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&K7(this,null))};
g.h.SU=function(a){I7("Receiver availability updated: "+a);if(!this.la()){var b=J7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;J7(this)!=b&&this.U("yt-remote-cast2-availability-change",J7(this))}};
g.h.fH=function(){this.la()||(this.B=jGa(this),I7("Updating custom receivers: "+g.Gg(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(){this.sc("Failed to set custom receivers.")},this)),this.U("yt-remote-cast2-availability-change",J7(this)))};
H7.prototype.setLaunchParams=H7.prototype.hX;H7.prototype.setConnectedScreenStatus=H7.prototype.gX;H7.prototype.stopSession=H7.prototype.lY;H7.prototype.getCastSession=H7.prototype.kY;H7.prototype.requestSession=H7.prototype.requestSession;H7.prototype.init=H7.prototype.init;H7.prototype.dispose=H7.prototype.dispose;var Q7=[];g.h=V7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";W7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.eg=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.A=a.seekableEnd,this.H=a.duration,this.J=a.loadedTime,this.B=a.liveIngestionTime,this.D=!(0,window.isNaN)(this.B))};
g.h.sb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.D?this.H+X7(this):this.H};
g.h.clone=function(){return new V7(a8(this))};g.C(c8,g.dG);g.h=c8.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.A,i8(this,"play")):h8(this,"play"),g8(this,1,Z7(d8(this))),this.U("remotePlayerChange")):e8(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.A,i8(this,"pause")):h8(this,"pause"),g8(this,2,Z7(d8(this))),this.U("remotePlayerChange")):e8(this,this.pause)};
g.h.bH=function(a){if(1==this.o){if(this.A){var b=d8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.sb()||3==b.playerState?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.A,i8(this,"seekTo",{newTime:a}))}else h8(this,"seekTo",{newTime:a});g8(this,3,a);this.U("remotePlayerChange")}else e8(this,g.Ca(this.bH,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.A,i8(this,"stopVideo")):h8(this,"stopVideo");var a=d8(this);a.index=-1;a.videoId="";W7(a);f8(this,a);this.U("remotePlayerChange")}else e8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=d8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.B)(function(){m7("CP","set receiver volume: "+d)},this),(0,g.B)(function(){this.sc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.B)(function(){m7("CP","set receiver muted: "+b)},this),(0,g.B)(function(){this.sc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);h8(this,"setVolume",e)}c.muted=b;c.volume=a;f8(this,c)}else e8(this,g.Ca(this.setVolume,a,b))};
g.h.UF=function(a,b){if(1==this.o){var c=d8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Gg(b.style),g.ec(d,c.o));h8(this,"setSubtitlesTrack",d);f8(this,c)}else e8(this,g.Ca(this.UF,a,b))};
g.h.Mx=function(a,b){if(1==this.o){h8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Nb.id});var c=d8(this);c.audioTrackId=b.Nb.id;f8(this,c)}else e8(this,g.Ca(this.Mx,a,b))};
g.h.aH=function(a,b){if(1==this.o){if(a&&b){var c=d8(this);$7(c,a,b);f8(this,c)}h8(this,"previous")}else e8(this,g.Ca(this.aH,a,b))};
g.h.ZG=function(a,b){if(1==this.o){if(a&&b){var c=d8(this);$7(c,a,b);f8(this,c)}h8(this,"next")}else e8(this,g.Ca(this.ZG,a,b))};
g.h.Yz=function(){1==this.o?h8(this,"dismissAutoplay"):e8(this,this.Yz)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.U("proxyStateChange",a,this.o)}c8.fa.dispose.call(this)};
g.h.X=function(){wGa(this);this.C=null;this.D.clear();b8(this,null);c8.fa.X.call(this)};
g.h.Nx=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.SC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.JU=function(a,b){this.U(a,b)};
g.h.gS=function(a){if(!a)this.cn(null),b8(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=d8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)m7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,f8(this,b)}};
g.h.cn=function(a){m7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),xGa(this),this.U("remotePlayerChange")};
g.h.fS=function(a){a?(xGa(this),this.U("remotePlayerChange")):this.cn(null)};
g.h.tS=function(){var a=tGa();a&&b8(this,a)};
g.h.sc=function(a){m7("CP",a)};g.C(j8,g.dG);g.h=j8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.jb.listId=c);this.jb.videoId=d;this.jb.index=k||0;this.jb.state=3;Y7(this.jb,m);this.C="UNSUPPORTED";k8("Connecting with setPlaylist and params: "+g.Gg(l));this.o.connect({method:"setPlaylist",
params:g.Gg(l)},a,SEa())}else k8("Connecting without params"),this.o.connect({},a,SEa());zGa(this)};
g.h.dispose=function(){this.la()||(this.U("beforeDispose"),l8(this,3));j8.fa.dispose.call(this)};
g.h.X=function(){m8(this);o8(this);n8(this);g.yE(this.J);this.J=window.NaN;g.yE(this.K);this.K=window.NaN;this.B=null;g.OF(this.V);this.V.length=0;this.o.dispose();j8.fa.X.call(this);this.C=this.G=this.A=this.jb=this.o=null};
g.h.lL=function(){this.F(2)};
g.h.kS=function(){k8("Channel opened");this.O&&(this.O=!1,n8(this),this.M=g.wE((0,g.B)(function(){k8("Timing out waiting for a screen.");this.F(1)},this),15E3));
WEa(JFa(this.o),this.ba)};
g.h.hS=function(){k8("Channel closed");(0,window.isNaN)(this.D)?z6(!0):z6();this.dispose()};
g.h.iS=function(a){z6();(0,window.isNaN)(this.H())?(k8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,k8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),l8(this,2))};
g.h.jS=function(a){a.params?k8("Received: action="+a.action+", params="+g.Gg(a.params)):k8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.xx(a.params.devices);this.A=(0,g.J)(a,function(a){return new n6(a)});
a=!!g.Ha(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
CGa(this,a);break;case "loungeScreenDisconnected":g.Ta(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
CGa(this,!1);break;case "remoteConnected":var b=new n6(g.xx(a.params.device));g.Ha(this.A,function(a){return b?a.id==b.id:!1})||g.Qa(this.A,b);
break;case "remoteDisconnected":b=new n6(g.xx(a.params.device));g.Ta(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":EGa(this,a);break;case "nowPlaying":GGa(this,a);break;case "onStateChange":FGa(this,a);break;case "onAdStateChange":HGa(this,a);break;case "onVolumeChanged":IGa(this,a);break;case "onSubtitlesTrackChanged":DGa(this,a);break;case "nowAutoplaying":JGa(this,a);break;case "autoplayDismissed":this.U("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.U("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.U("autoplayModeChange",this.C);"DISABLED"==this.C&&this.U("autoplayDismissed");break;case "onHasPreviousNextChanged":KGa(this,a);break;case "requestAssistedSignIn":this.U("assistedSignInRequested",a.params.authCode);break;default:k8("Unrecognized action: "+a.action)}};
g.h.QW=function(){if(this.B){var a=this.B;this.B=null;this.jb.videoId!=a&&p8(this,"getNowPlaying")}};
j8.prototype.subscribe=j8.prototype.subscribe;j8.prototype.unsubscribeByKey=j8.prototype.de;j8.prototype.ia=function(){var a=3;this.la()||(a=0,(0,window.isNaN)(this.H())?h7(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
j8.prototype.getProxyState=j8.prototype.ia;j8.prototype.F=function(a){k8("Disconnecting with "+a);m8(this);this.U("beforeDisconnect",a);1==a&&z6();KFa(this.o,a);this.dispose()};
j8.prototype.disconnect=j8.prototype.F;j8.prototype.ga=function(){var a=this.jb;this.B&&(a=this.jb.clone(),$7(a,this.B,a.index));return a8(a)};
j8.prototype.getPlayerContextData=j8.prototype.ga;
j8.prototype.ma=function(a){var b=new V7(a);b.videoId&&b.videoId!=this.jb.videoId&&(this.B=b.videoId,g.yE(this.J),this.J=g.wE((0,g.B)(this.QW,this),5E3));var c=[];this.jb.listId==b.listId&&this.jb.videoId==b.videoId&&this.jb.index==b.index||c.push("remoteQueueChange");this.jb.playerState==b.playerState&&this.jb.volume==b.volume&&this.jb.muted==b.muted&&Z7(this.jb)==Z7(b)&&g.Gg(this.jb.o)==g.Gg(b.o)||c.push("remotePlayerChange");this.jb.reset(a);(0,g.D)(c,function(a){this.U(a)},this)};
j8.prototype.setPlayerContextData=j8.prototype.ma;j8.prototype.Z=function(){var a=this.o.F.id,b=g.Ha(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
j8.prototype.getOtherConnectedRemoteId=j8.prototype.Z;j8.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():window.NaN};
j8.prototype.getReconnectTimeout=j8.prototype.H;j8.prototype.aa=function(){return this.C||"UNSUPPORTED"};
j8.prototype.getAutoplayMode=j8.prototype.aa;j8.prototype.da=function(){return this.G||""};
j8.prototype.getAutoplayVideoId=j8.prototype.da;j8.prototype.wa=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.Du(a.o);a.start()}};
j8.prototype.reconnect=j8.prototype.wa;j8.prototype.ka=function(a,b){p8(this,a,b);BGa(this)};
j8.prototype.sendMessage=j8.prototype.ka;g.C(q8,q7);g.h=q8.prototype;g.h.De=function(a){return this.nd.$_gs(a)};
g.h.contains=function(a){return!!this.nd.$_c(a)};
g.h.get=function(a){return this.nd.$_g(a)};
g.h.start=function(){this.nd.$_st()};
g.h.add=function(a,b,c){this.nd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.nd.$_r(a,b,c)};
g.h.rr=function(a,b,c,d){this.nd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.A.length;a<b;++a)this.nd.$_ubk(this.A[a]);this.A.length=0;this.nd=null;q8.fa.X.call(this)};
g.h.hY=function(){this.U("screenChange")};
g.h.iU=function(){this.U("onlineScreenChange")};
z7.prototype.$_st=z7.prototype.start;z7.prototype.$_gspc=z7.prototype.iY;z7.prototype.$_gsppc=z7.prototype.eH;z7.prototype.$_c=z7.prototype.contains;z7.prototype.$_g=z7.prototype.get;z7.prototype.$_a=z7.prototype.add;z7.prototype.$_un=z7.prototype.rr;z7.prototype.$_r=z7.prototype.remove;z7.prototype.$_gs=z7.prototype.De;z7.prototype.$_gos=z7.prototype.dH;z7.prototype.$_s=z7.prototype.subscribe;z7.prototype.$_ubk=z7.prototype.de;var r8=null,s8=null,H8=null,w8=[];g.t(I8,g.L);g.h=I8.prototype;
g.h.X=function(){g.L.prototype.X.call(this);this.C.stop();this.F.stop();this.L.stop();this.O();this.o.unsubscribe("proxyStateChange",this.AE,this);this.o.unsubscribe("remotePlayerChange",this.fn,this);this.o.unsubscribe("remoteQueueChange",this.uq,this);this.o.unsubscribe("autoplayUpNext",this.YD,this);this.o.unsubscribe("previousNextChange",this.xE,this);this.o.unsubscribe("nowAutoplaying",this.pE,this);this.o.unsubscribe("autoplayDismissed",this.XD,this);this.o=this.D=null};
g.h.TC=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(L8(this)){if(!d8(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":d8(this.o).sb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.Zl(c[0],c[1]);break;case "control_subtitles_set_track":M8(this,c[0]);break;case "control_set_audio_track":c=c[0],L8(this)&&this.o.Mx(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();N8(this,0==c?void 0:c);break;case "control_seek":N8(this,c[0]);break;case "control_subtitles_set_track":M8(this,c[0]);break;case "control_set_audio_track":c=c[0],L8(this)&&this.o.Mx(this.A.getVideoData(1).videoId,c)}};
g.h.eS=function(a){this.L.gL(a)};
g.h.IX=function(a){this.TC("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.kG=function(){var a=this.A.Cc("captions","track");g.Xb(a)||M8(this,a)};
g.h.mE=function(a){if(L8(this)){this.o.unsubscribe("remotePlayerChange",this.fn,this);var b=Math.round(a.volume);a=!!a.muted;var c=d8(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.M.start();this.o.subscribe("remotePlayerChange",this.fn,this)}};
g.h.zT=function(){g.Xb(this.G)||WGa(this,this.G);this.H=!1};
g.h.AE=function(a,b){this.F.stop();2==b&&this.hG()};
g.h.fn=function(){if(L8(this)){this.C.stop();var a=d8(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.D.G=1;break;case 1082:case 1083:this.D.G=0;break;default:this.D.G=-1}switch(a.playerState){case 1081:case 1:K8(this,new g.zP(8));this.gG();break;case 1085:case 3:K8(this,new g.zP(9));break;case 1083:case 0:K8(this,new g.zP(2));this.K.stop();J8(this,this.A.getVideoData().lengthSeconds);break;case 1084:K8(this,new g.zP(4));break;case 2:K8(this,new g.zP(4));J8(this,Z7(a));
break;case -1:K8(this,new g.zP(64));break;case -1E3:K8(this,new g.zP(128,{errorCode:"mdx.remoteerror",message:"Este v\u00eddeo n\u00e3o est\u00e1 dispon\u00edvel para reprodu\u00e7\u00e3o remota."}))}a=d8(this.o).o;var b=this.G;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.G=a,WGa(this,a));a=d8(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.M.isActive()||
this.KG()}else VGa(this)};
g.h.xE=function(){this.A.U("mdxpreviousnextchange")};
g.h.uq=function(){L8(this)||VGa(this)};
g.h.jK=function(){this.o.Yz()};
g.h.YD=function(a){a&&(a=g.NE("/watch_queue_ajax",{method:"GET",dd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.B)(this.PV,this)}))&&(this.O=(0,g.B)(a.abort,a))};
g.h.PV=function(a,b){var c=new g.QO(g.X(this.A),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.U("mdxautoplayupnext",c)};
g.h.pE=function(a){(0,window.isNaN)(a)||this.A.U("mdxnowautoplaying",a)};
g.h.XD=function(){this.A.U("mdxautoplaycanceled")};
g.h.gQ=function(a,b){-1==d8(this.o).playerState?N8(this,a):b&&this.o.bH(a)};
g.h.KG=function(){if(L8(this)){var a=d8(this.o);this.B.Ka(this.V);a.muted?this.A.mute():this.A.ng();this.A.setVolume(a.volume);this.V=this.B.R(this.A,"onVolumeChange",this.mE)}};
g.h.gG=function(){this.C.stop();if(!this.o.la()){var a=d8(this.o);a.sb()&&K8(this,new g.zP(8));J8(this,Z7(a));this.C.start()}};
g.h.hG=function(){this.F.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.F.start()};g.t(O8,g.V);O8.prototype.D=function(a){YGa(this,a.state)};g.t(P8,g.rY);P8.prototype.L=function(){var a=this.B.Cc("remote","receivers");a&&1<a.length&&!this.B.Cc("remote","quickCast")?(this.J=g.gb(a,this.F,this),g.sY(this,(0,g.J)(a,this.F)),a=this.B.Cc("remote","currentReceiver"),this.Ff(this.F(a)),this.enable(!0)):this.enable(!1)};
P8.prototype.F=function(a){return a.key};
P8.prototype.Ef=function(a){return"cast-selector-receiver"==a?"Elenco...":this.J[a].name};
P8.prototype.Gd=function(a){g.rY.prototype.Gd.call(this,a);this.B.Xd("remote","currentReceiver",this.J[a]);this.D.Tb()};g.t(Q8,g.sU);g.h=Q8.prototype;g.h.create=function(){PGa(g.hN(g.X(this.player)));this.D.push(g.qG("yt-remote-before-disconnect",this.aS,this));this.D.push(g.qG("yt-remote-connection-change",this.TU,this));this.D.push(g.qG("yt-remote-receiver-availability-change",this.yE,this));this.D.push(g.qG("yt-remote-auto-connect",this.RU,this));this.D.push(g.qG("yt-remote-receiver-resumed",this.QU,this));this.yE()};
g.h.load=function(){this.player.jv();g.sU.prototype.load.call(this);this.C=new I8(this,this.player,this.o);var a=(a=UGa())?a.currentTime:0;var b=G8()?new c8(B8(),void 0):null;0==a&&b&&(a=Z7(d8(b)));0!=a&&(this.J=a||0,this.player.U("progresssync",a,void 0));XGa(this,this.F,this.F);g.L_(this.player.app,6)};
g.h.unload=function(){this.player.U("mdxautoplaycanceled");this.B=this.A;g.mf(this.C,this.o);this.o=this.C=null;g.sU.prototype.unload.call(this);g.L_(this.player.app,5)};
g.h.X=function(){g.rG(this.D);g.sU.prototype.X.call(this)};
g.h.Sm=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.TC.apply(this.C,[a].concat(g.ea(c)))};
g.h.bL=function(){return this.loaded?this.C.suggestion:null};
g.h.eg=function(){return this.o?d8(this.o).eg:!1};
g.h.hasNext=function(){return this.o?d8(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.UP=function(){var a=d8(this.o),b=this.player.getVideoData();return{allowSeeking:g.X(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Lc():!a.isAdPlaying()&&this.player.Lc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.B+X7(a):a.B,isPeggedToLive:1>=(a.D?a.A+X7(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+X7(a):a.A,seekableStart:0<a.C?a.C+X7(a):a.C}};
g.h.VP=function(){this.o&&this.o.ZG()};
g.h.WP=function(){this.o&&this.o.aH()};
g.h.aS=function(a){1==a&&(this.K=this.o?d8(this.o):null)};
g.h.TU=function(){var a=G8()?new c8(B8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.K=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.lf(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.player.getVideoData().videoId&&this.player.zC(a.videoId,Z7(a)));this.player.U("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.yE=function(){this.H=[this.A].concat(RGa());var a=C8()||this.A;R8(this,a);this.player.ya("onMdxReceiversChange")};
g.h.RU=function(){var a=C8();R8(this,a)};
g.h.QU=function(){this.B=C8()};
g.h.TP=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?T7():R8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&T7(),!0):!1}};
g.h.XP=function(){h8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Ec=function(){return!1};g.rX.remote=Q8;})(_yt_player);
